<a href="https://colab.research.google.com/github/lfilipeAndrade/Data-Analysis/blob/main/01_Computacao_com_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Computação com Numpy

In [ ]:
# Importando o módulo Numpy
import numpy as np

<h2>Criando Estruturas de Dados NumPy</h2>

In [ ]:
# Criando array unidimensional
array1 = np.array([10, 20, 30, 40]) 

In [ ]:
# Criando array bi-dimensional
array2 = np.array([[100, 83, 15],[42, 78, 0]]) 

In [ ]:
array1

array([10, 20, 30, 40])

In [ ]:
array2

array([[100,  83,  15],
       [ 42,  78,   0]])

In [ ]:
# Verificando o formato (shape) do array
array1.shape

(4,)

In [ ]:
# Verificando o formato (shape) do array
array2.shape

(2, 3)

In [ ]:
# Verificando o número de dimensões
array2.ndim

2

<h2>Em Python TUDO é objeto, com métodos e atributos</h2>

### Método - realiza ação no objeto
### Atributo - característica do objeto

In [ ]:
# Método
array2.max()

100

In [ ]:
# Atributo
array2.ndim

2

<h2>Criando estruturas de dados com arange</h2>

In [ ]:
array3 = np.arange(15)

In [ ]:
array3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
# Usando start/end (exclusive)
array4 = np.arange(0, 15, 5)

In [ ]:
array4

array([ 0,  5, 10])

<h2>Criando estruturas de dados com linspace</h2>

In [ ]:
# Argumentos: (start, end, number of elements)
array5 = np.linspace(0, 3, 4); array5

array([ 0.,  1.,  2.,  3.])

<h2>Criando estruturas de dados com outras funções</h2>

<h3>numpy.zeros</h3>

In [ ]:
# Array 10x8 de zeros
array6 = np.zeros((10, 8)); array6

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

<h3>numpy.ones</h3>

In [ ]:
# Array 2x3x2 de 1's
array7 = np.ones((2, 3, 2)); array7

array([[[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.]]])

<h3>numpy.eye</h3>

In [ ]:
# Produz uma Identitiy Matrix 
array8 = np.eye(3); array8

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

<h3>numpy.diag</h3>

In [ ]:
# Matriz diagonal
array9 = np.diag((2,1,4,6)); array9

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

<h3>numpy.random.rand</h3>

In [ ]:
# A função rand(n) produz uma sequência de números uniformemente distirbuídos com range de 0 a n
np.random.seed(100) # Set seed
array10 = np.random.rand(5); array10

array([ 0.54340494,  0.27836939,  0.42451759,  0.84477613,  0.00471886])

In [ ]:
# A função randn(n) produz uma sequência de números com distribuição normal (Gaussian)
array11 = np.random.randn(5); array11

array([ 0.35467445, -0.78606433, -0.2318722 ,  0.20797568,  0.93580797])

<h3>numpy.empty</h3>

In [ ]:
array12 = np.empty((3,2)); array12

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

<h3>numpy.tile</h3>

In [ ]:
np.array([[9, 4], [3, 7]])

array([[9, 4],
       [3, 7]])

In [ ]:
np.tile(np.array([[9, 4], [3, 7]]), 4)

array([[9, 4, 9, 4, 9, 4, 9, 4],
       [3, 7, 3, 7, 3, 7, 3, 7]])

In [ ]:
np.tile(np.array([[9, 4], [3, 7]]), (2,2))

array([[9, 4, 9, 4],
       [3, 7, 3, 7],
       [9, 4, 9, 4],
       [3, 7, 3, 7]])

<h2>Tipos de Dados NumPy</h2>

In [ ]:
array13 = np.array([8, -3, 5, 9], dtype = 'float')

In [ ]:
array13

array([ 8., -3.,  5.,  9.])

In [ ]:
array13.dtype

dtype('float64')

In [ ]:
array14 = np.array([2, 4, 6, 8])

In [ ]:
array14

array([2, 4, 6, 8])

In [ ]:
array14.dtype

dtype('int64')

In [ ]:
array15 = np.array([2.0, 4, 6, 8])

In [ ]:
array15.dtype

dtype('float64')

In [ ]:
array16 = np.array(['Análise','de','Dados','com Python'])

In [ ]:
array16.dtype

dtype('<U10')

In [ ]:
array17 = np.array([True, False, True])

In [ ]:
array17.dtype

dtype('bool')

In [ ]:
array18 = np.array([7, -3, 5.24])

In [ ]:
array18.dtype

dtype('float64')

In [ ]:
array18.astype(int)

array([ 7, -3,  5])

<h2>Operações com Arrays</h2>

In [ ]:
# Array começando por 0, com 30 elementos e multiplicado po 5
array19 = np.arange(0, 30) * 5

In [ ]:
array19

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145])

In [ ]:
array19 = np.arange(0, 30)

In [ ]:
array19

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
# Elevando um array a potência
array20 = np.arange(5) ** 4

In [ ]:
array20

array([  0,   1,  16,  81, 256])

In [ ]:
# Somando um número a cada elemento do array
array21 = np.arange(0, 30) + 1

In [ ]:
array21

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
array22 = np.arange(0, 30,3) + 3
array23 = np.arange(1,11)

In [ ]:
array22

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [ ]:
array23

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Subtração
array22 - array23

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
# Soma
array22 + array23

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [ ]:
# Divisão
array22 / array23

array([ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.])

In [ ]:
# Multiplicação
array22 * array23

array([  3,  12,  27,  48,  75, 108, 147, 192, 243, 300])

In [ ]:
# Podemos ainda comprar arrays
array22 > array23

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [ ]:
arr1 = np.array([True,False,True,False])
arr2 = np.array([False,False,True, False])
np.logical_and(arr1, arr2)

array([False, False,  True, False], dtype=bool)

### Podemos criar arrays com Python, sem usar o módulo NumPy. Porém o NumPy é muito mais rápido

In [ ]:
array_numpy = np.arange(1000)
%timeit array_numpy ** 4

10000 loops, best of 3: 43 µs per loop


In [ ]:
array_python = range(1000)
%timeit [array_python[i] ** 4 for i in array_python]

1000 loops, best of 3: 520 µs per loop


A métrica µs significa microsegundos.

# Fim