<a href="https://colab.research.google.com/github/lfilipeAndrade/Numpy/blob/main/Concatenate_Join_Split_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NumPy

NumPy oferece sequências de elementos que são mais eficientes que sequências padrões em Python.

In [2]:
import sys
import numpy as np


## Concatenando Arrays

In [3]:
array1 = np.ones(4)

In [4]:
array2 = np.arange(15)

In [5]:
array_conc = np.concatenate((array1, array2))

In [6]:
array_conc

array([ 1.,  1.,  1.,  1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,
        9., 10., 11., 12., 13., 14.])

## Joining Arrays

In [7]:
a = np.ones((3,3))
b = np.zeros((3,3))

In [8]:
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
?np.vstack

In [11]:
?np.hstack

In [12]:
# Primeiro preenche as linhas
np.vstack((a,b))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
# Primeiro preenche as colunas
np.hstack((a,b))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [14]:
# Joining arrays
a = np.array([0, 1, 2])
b = np.array([3, 4, 5])
c = np.array([6, 7, 8])

In [15]:
?np.column_stack

In [16]:
?np.row_stack

In [17]:
np.column_stack((a, b, c))

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [18]:
np.row_stack((a, b, c))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Split Arrays

In [19]:
array3 = np.arange(16).reshape((4,4)); array3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [20]:
[array3_p1, array3_p2] = np.hsplit(array3, 2)

In [21]:
array3_p1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [22]:
array3_p2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [23]:
[array3_p1, array3_p2] = np.vsplit(array3, 2)

In [24]:
array3_p1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [25]:
array3_p2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## Gravando e Cerragendo Dados com NumPy

In [26]:
dados = array3

In [27]:
np.save('dados_saved_v1', dados)

In [28]:
loaded_data = np.load('dados_saved_v1.npy')

In [29]:
loaded_data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])