<a href="https://colab.research.google.com/github/lfilipeAndrade/Numpy/blob/main/Operations_using_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## NumPy

NumPy oferece sequências de elementos que são mais eficientes que sequências padrões em Python.

In [3]:
import sys
import numpy as np

In [4]:
# Criando um array NumPy
array1 = np.arange(15)

In [5]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
# Help
?array1

In [7]:
array1.mean()

7.0

In [8]:
array1.sum()

105

In [9]:
array1.min()

0

In [10]:
array1.max()

14

In [11]:
array1.std()

4.320493798938574

## Utilizando List Compreheension em Arrays NumPy

In [12]:
# Utilizando lists compreheension em arrays NumPy
[x * x for x in array1]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196]

In [13]:
# Utilizando lists compreheension em arrays NumPy
[x * x for x in array1 if x % 2 == 0]

[0, 4, 16, 36, 64, 100, 144, 196]

## Utilizando Função Lambda em Arrays NumPy

In [14]:
# Utilizando expressão lambda
list(filter(lambda x: x % 2 == 0, array1))

[0, 2, 4, 6, 8, 10, 12, 14]

In [15]:
# Atenção com a notação
array1 % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True])

In [16]:
# # Atenção com a notação
array1[array1 % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

## Avaliando a Performance

In [17]:
# Performance usando list compreheension
%timeit [x for x in array1 if x % 2 == 0]

100000 loops, best of 5: 10.1 µs per loop


In [18]:
# Performance usando NumPy
%timeit array1[array1 % 2 == 0]

The slowest run took 15.70 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 5: 2.7 µs per loop


## Usando Operadores Lógicos

In [19]:
array1 > 8

array([False, False, False, False, False, False, False, False, False,
        True,  True,  True,  True,  True,  True])

In [20]:
array1[array1 > 8]

array([ 9, 10, 11, 12, 13, 14])

In [21]:
# Operador lógico and 
(array1 > 9) & (array1 < 12)

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True, False, False, False])

In [22]:
# Operador lógico or
(array1 > 13) | (array1 < 12)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False,  True])

In [23]:
# Operador lógico or
array1[(array1 > 13) | (array1 < 12)]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 14])

In [24]:
# Criando um array NumPy com list comprehension
array2 = np.array([x ** 3 for x in range(15)])

In [25]:
array2

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000,
       1331, 1728, 2197, 2744])

In [26]:
# Criando um array NumPy com list comprehension
array2 = np.array([True for x in range(15)])

In [27]:
array2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [28]:
# Usando um array como índice para outro array
array1[array2]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])